project:
  type: website
  output-dir: _output

website:
  title: "Personal Study"
  description: "Machine Learning Paper Summaries and Notes"
  sidebar:
    style: docked
    search: true
    contents:
      - section: "Topics"
        contents:
          - href: posts/category-diffusion.qmd
            text: Diffusion models
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/junhyun-nam/blog
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
execute:
  freeze: auto
